<?php
/**
 * Fossil (classic Tibia 7.x) experience table.
 *
 * CipSoft never published a formula, but the table at
 * https://www.tibia.com/library/?subtopic=experiencetable is generated by a
 * cubic, and it has been verified exact against the published values — levels
 * 1-20 plus the 100 / 150 / 200 checkpoints all match to the point:
 *
 *   total XP to reach level L       XP(L)  = 50/3 * (L^3 - 6L^2 + 17L - 12)
 *   XP to get from level L to L+1  dXP(L)  = 50   * (L^2 - 3L + 4)
 *
 * (The second is just XP(L+1) - XP(L) expanded.)
 *
 * Deriving instead of storing values keeps the table exact at any level, so
 * raising the ceiling once players outgrow it is a one-number change here.
 */

/** Highest level the Experience Table wiki page shows by default. */
const FOSSIL_EXP_MAX_LEVEL = 200;

/** Hard ceiling for the ?max= override, purely to bound the page size. */
const FOSSIL_EXP_LEVEL_CEILING = 1000;

/**
 * Total experience a character has on reaching $level (level 1 = 0).
 *
 * The polynomial is always divisible by 3 — modulo 3 it reduces to L^3 + 2L,
 * and L^3 = L by Fermat, so it is 3L = 0 — which means the division is exact
 * and the result stays an integer at every level.
 */
function fossil_exp_total(int $level): int
{
    if ($level <= 1) {
        return 0;
    }
    $poly = $level * $level * $level - 6 * $level * $level + 17 * $level - 12;
    return 50 * intdiv($poly, 3);
}

/** Experience still to earn while at $level before advancing to $level + 1. */
function fossil_exp_to_next(int $level): int
{
    if ($level < 1) {
        return 0;
    }
    return 50 * ($level * $level - 3 * $level + 4);
}

/**
 * Rows for the experience table, level 1 .. $maxLevel.
 *
 * Each row carries the level, the `gain` needed to reach it from the level
 * below (0 at level 1, which everyone starts at) and the `total` experience a
 * character has the moment they get there.
 */
function fossil_exp_table(int $maxLevel = FOSSIL_EXP_MAX_LEVEL): array
{
    $rows = [];
    for ($level = 1; $level <= $maxLevel; $level++) {
        $rows[] = [
            'level' => $level,
            'gain'  => $level === 1 ? 0 : fossil_exp_to_next($level - 1),
            'total' => fossil_exp_total($level),
        ];
    }
    return $rows;
}
